# https://www.jianshu.com/p/3c5de0c4ca76
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggplot2)
library(patchwork)
library(scales)
library(RColorBrewer)
library(stringr)
library(tidyr)
library(DOSE)
library(enrichplot)
library(dplyr)
library(pathview)
args=commandArgs(T) # args = c("C:\\Users\\dell\\Desktop\\all.c2n.cf2.fc2.featureCount.DESeq2.txt", "C:\\Users\\dell\\Desktop\\all.c2n.cf2.fc2.featureCount.DESeq2.GO.pdf")
args = c("C:\\Users\\dell\\Desktop\\all.c2n.cf2.fc2.featureCount.DESeq2.txt", "C:\\Users\\dell\\Desktop\\all.c2n.cf2.fc2.featureCount.DESeq2.GO.pdf")

cut_off_qvalue = 0.05
cut_off_logFC = 1

mydat = read.table(args[1], header=T, sep="\t")
mydat$change = ifelse(mydat$padj <= cut_off_qvalue & abs(mydat$log2FoldChange) >= cut_off_logFC, ifelse(mydat$log2FoldChange > cut_off_logFC ,'Up','Down'), 'Stable')
mydat$rawid = rownames(mydat)
mydat = mydat %>% separate(col = rawid, into = c("geneid","num"), sep="\\.")
entrezid = bitr(mydat$geneid, fromType = "ENSEMBL", toType = c("SYMBOL","ENTREZID"), OrgDb = org.Hs.eg.db,drop =  FALSE)
names(entrezid)[1] = "geneid"
genedat = left_join(mydat, entrezid, by="geneid")
genedat <- na.omit(genedat)
upgene = genedat[genedat$change == "Up", ]
downgene = genedat[genedat$change == "Down", ]

upgeneList = upgene$log2FoldChange
names(upgeneList) = upgene$ENTREZID
upgeneList <- sort(upgeneList, decreasing = TRUE)
downgeneList = downgene$log2FoldChange
names(downgeneList) = downgene$ENTREZID
downgeneList <- sort(downgeneList, decreasing = TRUE)
diffgeneList = c(upgeneList, downgeneList)

allgeneList = genedat$log2FoldChange
names(allgeneList) = genedat$ENTREZID
allgeneList <- sort(allgeneList, decreasing = TRUE)


pdf(paste0(args[2],"upgene.pdf"), width=10, height=20)
############################# up gene result ###################################
upgenekegg = enrichKEGG(gene = names(upgeneList), organism = 'hsa', keyType = 'kegg') # kegg
upgenekegg2 = enrichKEGG(gene = names(upgeneList), organism = 'hsa', keyType = 'kegg', universe = genedat$ENTREZID)
write.table(as.data.frame(upgenekegg), paste0(args[1],".up.kegg.txt"), sep="\t", quote=F)
write.table(as.data.frame(upgenekegg2), paste0(args[1],".up.kegg2.txt"), sep="\t", quote=F)
p1 = dotplot(upgenekegg, showCategory=20) + labs(title = "up kegg") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p1)
p2 = barplot(upgenekegg, showCategory=20) + labs(title = "up kegg") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p2)
a1 = cnetplot(setReadable(upgenekegg, 'org.Hs.eg.db', 'ENTREZID')) + labs(title = "up kegg")
a2 = cnetplot(setReadable(upgenekegg, 'org.Hs.eg.db', 'ENTREZID'), foldChange = upgeneList) + labs(title = "up kegg")
a3 = cnetplot(setReadable(upgenekegg, 'org.Hs.eg.db', 'ENTREZID'), categorySize="pvalue", foldChange = upgeneList) + labs(title = "up kegg")
a4 = cnetplot(setReadable(upgenekegg, 'org.Hs.eg.db', 'ENTREZID'), circular = TRUE, colorEdge = TRUE, foldChange = upgeneList) + labs(title = "up kegg")
a5 = heatplot(setReadable(upgenekegg, 'org.Hs.eg.db', 'ENTREZID'), foldChange = upgeneList) + labs(title = "up kegg")
a6 = emapplot(pairwise_termsim(upgenekegg)) + labs(title = "up kegg")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
# hsa04060 <- pathview(gene.data  = names(upgeneList), pathway.id = "hsa04060", species = "hsa", limit = list(gene=max(abs(upgeneList)), cpd=1))

upgenego = enrichGO(gene = names(upgeneList), OrgDb = org.Hs.eg.db, keyType = 'ENTREZID', ont = "ALL", readable = T) # go
upgenego2 = enrichGO(gene = names(upgeneList), OrgDb = org.Hs.eg.db, keyType = 'ENTREZID', ont = "ALL", readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(upgenego), paste0(args[1],".up.go.txt"), sep="\t", quote=F)
write.table(as.data.frame(upgenego2), paste0(args[1],".up.go2.txt"), sep="\t", quote=F)
p3 = dotplot(upgenego,showCategory=20,split="ONTOLOGY") + facet_grid(ONTOLOGY~.,scale='free') + labs(title = "up go") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p3)
p4 = barplot(upgenego, showCategory=20) + labs(title = "up go") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p4)
a1 = cnetplot(upgenego) + labs(title = "up go")
a2 = cnetplot(upgenego, foldChange = upgeneList) + labs(title = "up go")
a3 = cnetplot(upgenego, categorySize="pvalue", foldChange = upgeneList) + labs(title = "up go")
a4 = cnetplot(upgenego, circular = TRUE, colorEdge = TRUE, foldChange = upgeneList) + labs(title = "up go")
a5 = heatplot(upgenego, foldChange = upgeneList) + labs(title = "up go")
a6 = emapplot(pairwise_termsim(upgenego)) + labs(title = "up go")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

upgenedgn <- enrichDGN(gene = names(upgeneList), readable = T) # 疾病关联 # DisGeNET
upgenedgn2 <- enrichDGN(gene = names(upgeneList), readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(upgenedgn), paste0(args[1],".up.dgn.txt"), sep="\t", quote=F)
write.table(as.data.frame(upgenedgn2), paste0(args[1],".up.dgn2.txt"), sep="\t", quote=F)
p5 = dotplot(upgenedgn, showCategory=20) + labs(title = "up DisGeNET") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p5)
p6 = barplot(upgenedgn, showCategory=20) + labs(title = "up DisGeNET") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p6)
a1 = cnetplot(upgenedgn) + labs(title = "up DisGeNET")
a2 = cnetplot(upgenedgn, foldChange = upgeneList) + labs(title = "up DisGeNET")
a3 = cnetplot(upgenedgn, categorySize="pvalue", foldChange = upgeneList) + labs(title = "up DisGeNET")
a4 = cnetplot(upgenedgn, circular = TRUE, colorEdge = TRUE, foldChange = upgeneList) + labs(title = "up DisGeNET")
a5 = heatplot(upgenedgn, foldChange = upgeneList) + labs(title = "up DisGeNET")
a6 = emapplot(pairwise_termsim(upgenedgn)) + labs(title = "up DisGeNET")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

upgenedo = enrichDO(gene = names(upgeneList), ont = "DO", readable = T) # 疾病
upgenedo2 = enrichDO(gene = names(upgeneList), ont = "DO", readable = T, universe = genedat$ENTREZID) # 疾病
write.table(as.data.frame(upgenedo), paste0(args[1],".up.do.txt"), sep="\t", quote=F)
write.table(as.data.frame(upgenedo2), paste0(args[1],".up.do2.txt"), sep="\t", quote=F)
p7 = dotplot(upgenedo, showCategory=20) + labs(title = "up disease") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p7)
p8 = barplot(upgenedo, showCategory=20) + labs(title = "up disease") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p8)
a1 = cnetplot(upgenedo) + labs(title = "up disease")
a2 = cnetplot(upgenedo, foldChange = upgeneList) + labs(title = "up disease")
a3 = cnetplot(upgenedo, categorySize="pvalue", foldChange = upgeneList) + labs(title = "up disease")
a4 = cnetplot(upgenedo, circular = TRUE, colorEdge = TRUE, foldChange = upgeneList) + labs(title = "up disease")
a5 = heatplot(upgenedo, foldChange = upgeneList) + labs(title = "up disease")
a6 = emapplot(pairwise_termsim(upgenedo)) + labs(title = "up disease")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

upgenencg = enrichNCG(gene = names(upgeneList), readable = T) # 癌症
upgenencg2 = enrichNCG(gene = names(upgeneList), readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(upgenencg), paste0(args[1],".up.ncg.txt"), sep="\t", quote=F)
write.table(as.data.frame(upgenencg2), paste0(args[1],".up.ncg2.txt"), sep="\t", quote=F)
p9 = dotplot(upgenencg, showCategory=20) + labs(title = "up cancer") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p9)
p10 = barplot(upgenencg, showCategory=20) + labs(title = "up cancer") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p10)
a1 = cnetplot(upgenencg) + labs(title = "up cancer")
a2 = cnetplot(upgenencg, foldChange = upgeneList) + labs(title = "up cancer")
a3 = cnetplot(upgenencg, categorySize="pvalue", foldChange = upgeneList) + labs(title = "up cancer")
a4 = cnetplot(upgenencg, circular = TRUE, colorEdge = TRUE, foldChange = upgeneList) + labs(title = "up cancer")
a5 = heatplot(upgenencg, foldChange = upgeneList) + labs(title = "up cancer")
a6 = emapplot(pairwise_termsim(upgenencg)) + labs(title = "up cancer")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
dev.off()



pdf(paste0(args[2],"downgene.pdf"), width=10, height=20)
############################# down gene result ###################################
downgenekegg = enrichKEGG(gene = names(downgeneList), organism = 'hsa', keyType = 'kegg') # kegg
downgenekegg2 = enrichKEGG(gene = names(downgeneList), organism = 'hsa', keyType = 'kegg', universe = genedat$ENTREZID)
write.table(as.data.frame(downgenekegg), paste0(args[1],".down.kegg.txt"), sep="\t", quote=F)
write.table(as.data.frame(downgenekegg2), paste0(args[1],".down.kegg2.txt"), sep="\t", quote=F)
p1 = dotplot(downgenekegg, showCategory=20) + labs(title = "down kegg") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p1)
p2 = barplot(downgenekegg, showCategory=20) + labs(title = "down kegg") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p2)
a1 = cnetplot(setReadable(downgenekegg, 'org.Hs.eg.db', 'ENTREZID')) + labs(title = "down kegg")
a2 = cnetplot(setReadable(downgenekegg, 'org.Hs.eg.db', 'ENTREZID'), foldChange = downgeneList) + labs(title = "down kegg")
a3 = cnetplot(setReadable(downgenekegg, 'org.Hs.eg.db', 'ENTREZID'), categorySize="pvalue", foldChange = downgeneList) + labs(title = "down kegg")
a4 = cnetplot(setReadable(downgenekegg, 'org.Hs.eg.db', 'ENTREZID'), circular = TRUE, colorEdge = TRUE, foldChange = downgeneList) + labs(title = "down kegg")
a5 = heatplot(setReadable(downgenekegg, 'org.Hs.eg.db', 'ENTREZID'), foldChange = downgeneList) + labs(title = "down kegg")
a6 = emapplot(pairwise_termsim(downgenekegg)) + labs(title = "down kegg")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
# hsa04060 <- pathview(gene.data  = names(downgeneList), pathway.id = "hsa04060", species = "hsa", limit = list(gene=max(abs(downgeneList)), cpd=1))

downgenego = enrichGO(gene = names(downgeneList), OrgDb = org.Hs.eg.db, keyType = 'ENTREZID', ont = "ALL", readable = T) # go
downgenego2 = enrichGO(gene = names(downgeneList), OrgDb = org.Hs.eg.db, keyType = 'ENTREZID', ont = "ALL", readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(downgenego), paste0(args[1],".down.go.txt"), sep="\t", quote=F)
write.table(as.data.frame(downgenego2), paste0(args[1],".down.go2.txt"), sep="\t", quote=F)
p3 = dotplot(downgenego,showCategory=20,split="ONTOLOGY") + facet_grid(ONTOLOGY~.,scale='free') + labs(title = "down go") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p3)
p4 = barplot(downgenego, showCategory=20) + labs(title = "down go") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p4)
a1 = cnetplot(downgenego) + labs(title = "down go")
a2 = cnetplot(downgenego, foldChange = downgeneList) + labs(title = "down go")
a3 = cnetplot(downgenego, categorySize="pvalue", foldChange = downgeneList) + labs(title = "down go")
a4 = cnetplot(downgenego, circular = TRUE, colorEdge = TRUE, foldChange = downgeneList) + labs(title = "down go")
a5 = heatplot(downgenego, foldChange = downgeneList) + labs(title = "down go")
a6 = emapplot(pairwise_termsim(downgenego)) + labs(title = "down go")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

downgenedgn <- enrichDGN(gene = names(downgeneList), readable = T) # 疾病关联 # DisGeNET
downgenedgn2 <- enrichDGN(gene = names(downgeneList), readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(downgenedgn), paste0(args[1],".down.dgn.txt"), sep="\t", quote=F)
write.table(as.data.frame(downgenedgn2), paste0(args[1],".down.dgn2.txt"), sep="\t", quote=F)
p5 = dotplot(downgenedgn, showCategory=20) + labs(title = "down DisGeNET") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p5)
p6 = barplot(downgenedgn, showCategory=20) + labs(title = "down DisGeNET") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p6)
a1 = cnetplot(downgenedgn) + labs(title = "down DisGeNET")
a2 = cnetplot(downgenedgn, foldChange = downgeneList) + labs(title = "down DisGeNET")
a3 = cnetplot(downgenedgn, categorySize="pvalue", foldChange = downgeneList) + labs(title = "down DisGeNET")
a4 = cnetplot(downgenedgn, circular = TRUE, colorEdge = TRUE, foldChange = downgeneList) + labs(title = "down DisGeNET")
a5 = heatplot(downgenedgn, foldChange = downgeneList) + labs(title = "down DisGeNET")
a6 = emapplot(pairwise_termsim(downgenedgn)) + labs(title = "down DisGeNET")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

downgenedo = enrichDO(gene = names(downgeneList), ont = "DO", readable = T) # 疾病
downgenedo2 = enrichDO(gene = names(downgeneList), ont = "DO", readable = T, universe = genedat$ENTREZID) # 疾病
write.table(as.data.frame(downgenedo), paste0(args[1],".down.do.txt"), sep="\t", quote=F)
write.table(as.data.frame(downgenedo2), paste0(args[1],".down.do2.txt"), sep="\t", quote=F)
p7 = dotplot(downgenedo, showCategory=20) + labs(title = "down disease") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p7)
p8 = barplot(downgenedo, showCategory=20) + labs(title = "down disease") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p8)
a1 = cnetplot(downgenedo) + labs(title = "down disease")
a2 = cnetplot(downgenedo, foldChange = downgeneList) + labs(title = "down disease")
a3 = cnetplot(downgenedo, categorySize="pvalue", foldChange = downgeneList) + labs(title = "down disease")
a4 = cnetplot(downgenedo, circular = TRUE, colorEdge = TRUE, foldChange = downgeneList) + labs(title = "down disease")
a5 = heatplot(downgenedo, foldChange = downgeneList) + labs(title = "down disease")
a6 = emapplot(pairwise_termsim(downgenedo)) + labs(title = "down disease")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

downgenencg = enrichNCG(gene = names(downgeneList), readable = T) # 癌症
downgenencg2 = enrichNCG(gene = names(downgeneList), readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(downgenencg), paste0(args[1],".down.ncg.txt"), sep="\t", quote=F)
write.table(as.data.frame(downgenencg2), paste0(args[1],".down.ncg2.txt"), sep="\t", quote=F)
p9 = dotplot(downgenencg, showCategory=20) + labs(title = "down cancer") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p9)
p10 = barplot(downgenencg, showCategory=20) + labs(title = "down cancer") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p10)
a1 = cnetplot(downgenencg) + labs(title = "down cancer")
a2 = cnetplot(downgenencg, foldChange = downgeneList) + labs(title = "down cancer")
a3 = cnetplot(downgenencg, categorySize="pvalue", foldChange = downgeneList) + labs(title = "down cancer")
a4 = cnetplot(downgenencg, circular = TRUE, colorEdge = TRUE, foldChange = downgeneList) + labs(title = "down cancer")
a5 = heatplot(downgenencg, foldChange = downgeneList) + labs(title = "down cancer")
a6 = emapplot(pairwise_termsim(downgenencg)) + labs(title = "down cancer")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
dev.off()


pdf(paste0(args[2],"diffgene.pdf"), width=10, height=20)
############################# diff gene result ###################################
diffgenekegg = enrichKEGG(gene = names(diffgeneList), organism = 'hsa', keyType = 'kegg') # kegg
diffgenekegg2 = enrichKEGG(gene = names(diffgeneList), organism = 'hsa', keyType = 'kegg', universe = genedat$ENTREZID)
write.table(as.data.frame(diffgenekegg), paste0(args[1],".diff.kegg.txt"), sep="\t", quote=F)
write.table(as.data.frame(diffgenekegg2), paste0(args[1],".diff.kegg2.txt"), sep="\t", quote=F)
p1 = dotplot(diffgenekegg, showCategory=20) + labs(title = "diff kegg") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p1)
p2 = barplot(diffgenekegg, showCategory=20) + labs(title = "diff kegg") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p2)
a1 = cnetplot(setReadable(diffgenekegg, 'org.Hs.eg.db', 'ENTREZID')) + labs(title = "diff kegg")
a2 = cnetplot(setReadable(diffgenekegg, 'org.Hs.eg.db', 'ENTREZID'), foldChange = diffgeneList) + labs(title = "diff kegg")
a3 = cnetplot(setReadable(diffgenekegg, 'org.Hs.eg.db', 'ENTREZID'), categorySize="pvalue", foldChange = diffgeneList) + labs(title = "diff kegg")
a4 = cnetplot(setReadable(diffgenekegg, 'org.Hs.eg.db', 'ENTREZID'), circular = TRUE, colorEdge = TRUE, foldChange = diffgeneList) + labs(title = "diff kegg")
a5 = heatplot(setReadable(diffgenekegg, 'org.Hs.eg.db', 'ENTREZID'), foldChange = diffgeneList) + labs(title = "diff kegg")
a6 = emapplot(pairwise_termsim(diffgenekegg)) + labs(title = "diff kegg")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
# hsa04060 <- pathview(gene.data  = names(diffgeneList), pathway.id = "hsa04060", species = "hsa", limit = list(gene=max(abs(diffgeneList)), cpd=1))

diffgenego = enrichGO(gene = names(diffgeneList), OrgDb = org.Hs.eg.db, keyType = 'ENTREZID', ont = "ALL", readable = T) # go
diffgenego2 = enrichGO(gene = names(diffgeneList), OrgDb = org.Hs.eg.db, keyType = 'ENTREZID', ont = "ALL", readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(diffgenego), paste0(args[1],".diff.go.txt"), sep="\t", quote=F)
write.table(as.data.frame(diffgenego2), paste0(args[1],".diff.go2.txt"), sep="\t", quote=F)
p3 = dotplot(diffgenego,showCategory=20,split="ONTOLOGY") + facet_grid(ONTOLOGY~.,scale='free') + labs(title = "diff go") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p3)
p4 = barplot(diffgenego, showCategory=20) + labs(title = "diff go") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p4)
a1 = cnetplot(diffgenego) + labs(title = "diff go")
a2 = cnetplot(diffgenego, foldChange = diffgeneList) + labs(title = "diff go")
a3 = cnetplot(diffgenego, categorySize="pvalue", foldChange = diffgeneList) + labs(title = "diff go")
a4 = cnetplot(diffgenego, circular = TRUE, colorEdge = TRUE, foldChange = diffgeneList) + labs(title = "diff go")
a5 = heatplot(diffgenego, foldChange = diffgeneList) + labs(title = "diff go")
a6 = emapplot(pairwise_termsim(diffgenego)) + labs(title = "diff go")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

diffgenedgn <- enrichDGN(gene = names(diffgeneList), readable = T) # 疾病关联 # DisGeNET
diffgenedgn2 <- enrichDGN(gene = names(diffgeneList), readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(diffgenedgn), paste0(args[1],".diff.dgn.txt"), sep="\t", quote=F)
write.table(as.data.frame(diffgenedgn2), paste0(args[1],".diff.dgn2.txt"), sep="\t", quote=F)
p5 = dotplot(diffgenedgn, showCategory=20) + labs(title = "diff DisGeNET") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p5)
p6 = barplot(diffgenedgn, showCategory=20) + labs(title = "diff DisGeNET") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p6)
a1 = cnetplot(diffgenedgn) + labs(title = "diff DisGeNET")
a2 = cnetplot(diffgenedgn, foldChange = diffgeneList) + labs(title = "diff DisGeNET")
a3 = cnetplot(diffgenedgn, categorySize="pvalue", foldChange = diffgeneList) + labs(title = "diff DisGeNET")
a4 = cnetplot(diffgenedgn, circular = TRUE, colorEdge = TRUE, foldChange = diffgeneList) + labs(title = "diff DisGeNET")
a5 = heatplot(diffgenedgn, foldChange = diffgeneList) + labs(title = "diff DisGeNET")
a6 = emapplot(pairwise_termsim(diffgenedgn)) + labs(title = "diff DisGeNET")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

diffgenedo = enrichDO(gene = names(diffgeneList), ont = "DO", readable = T) # 疾病
diffgenedo2 = enrichDO(gene = names(diffgeneList), ont = "DO", readable = T, universe = genedat$ENTREZID) # 疾病
write.table(as.data.frame(diffgenedo), paste0(args[1],".diff.do.txt"), sep="\t", quote=F)
write.table(as.data.frame(diffgenedo2), paste0(args[1],".diff.do2.txt"), sep="\t", quote=F)
p7 = dotplot(diffgenedo, showCategory=20) + labs(title = "diff disease") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p7)
p8 = barplot(diffgenedo, showCategory=20) + labs(title = "diff disease") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p8)
a1 = cnetplot(diffgenedo) + labs(title = "diff disease")
a2 = cnetplot(diffgenedo, foldChange = diffgeneList) + labs(title = "diff disease")
a3 = cnetplot(diffgenedo, categorySize="pvalue", foldChange = diffgeneList) + labs(title = "diff disease")
a4 = cnetplot(diffgenedo, circular = TRUE, colorEdge = TRUE, foldChange = diffgeneList) + labs(title = "diff disease")
a5 = heatplot(diffgenedo, foldChange = diffgeneList) + labs(title = "diff disease")
a6 = emapplot(pairwise_termsim(diffgenedo)) + labs(title = "diff disease")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)

diffgenencg = enrichNCG(gene = names(diffgeneList), readable = T) # 癌症
diffgenencg2 = enrichNCG(gene = names(diffgeneList), readable = T, universe = genedat$ENTREZID)
write.table(as.data.frame(diffgenencg), paste0(args[1],".diff.ncg.txt"), sep="\t", quote=F)
write.table(as.data.frame(diffgenencg2), paste0(args[1],".diff.ncg2.txt"), sep="\t", quote=F)
p9 = dotplot(diffgenencg, showCategory=20) + labs(title = "diff cancer") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p9)
p10 = barplot(diffgenencg, showCategory=20) + labs(title = "diff cancer") + theme_bw() + theme(legend.position = "none", panel.grid=element_blank(),axis.line=element_line(linewidth=0,colour="black"))
print(p10)
a1 = cnetplot(diffgenencg) + labs(title = "diff cancer")
a2 = cnetplot(diffgenencg, foldChange = diffgeneList) + labs(title = "diff cancer")
a3 = cnetplot(diffgenencg, categorySize="pvalue", foldChange = diffgeneList) + labs(title = "diff cancer")
a4 = cnetplot(diffgenencg, circular = TRUE, colorEdge = TRUE, foldChange = diffgeneList) + labs(title = "diff cancer")
a5 = heatplot(diffgenencg, foldChange = diffgeneList) + labs(title = "diff cancer")
a6 = emapplot(pairwise_termsim(diffgenencg)) + labs(title = "diff cancer")
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
dev.off()



############################# GSEA ###################################
pdf(paste0(args[2],"GSEA.pdf"), width=10, height=20)
genekegggse = gseKEGG(gene = allgeneList, organism = 'hsa', keyType = 'kegg')
genegogse = gseGO(gene = allgeneList, ont = 'ALL', OrgDb = org.Hs.eg.db, keyType = "ENTREZID")
genencggsea <- gseNCG(gene = allgeneList)
genedgngsea <- gseDGN(gene = allgeneList)
genedogsea <- gseDO(gene = allgeneList)
p1 = ridgeplot(genekegggse)
p2 = ridgeplot(genegogse)
p3 = ridgeplot(genencggsea)
p4 = ridgeplot(genedgngsea)
p5 = ridgeplot(genedogsea)
print(p1)
print(p2)
print(p3)
print(p4)
print(p5)
dev.off()

