library(org.Hs.eg.db)
ensemblegene <- read.table("CNV.list",header=F)
transid  <- select(org.Hs.eg.db,keys=as.vector(ensemblegene[,1]),columns = c("GENENAME","SYMBOL","ENTREZID"),keytype = "ENSEMBL")
write.table(transid,"CNV_transid.txt",quote=F,row.name=F,sep="\t")

require(DOSE)
require(clusterProfiler)

egocc <- enrichGO(gene=transid$ENTREZID,OrgDb ="org.Hs.eg.db",ont="CC")
pdf("CNV_CC.dotplot.pdf",width=15,height=10)
dotplot(egocc, font.size=10,title="CNV gene CC",showCategory=15)
dev.off()
pdf("CNV_CC.map.pdf",width=10,height=10)
enrichMap(egocc, vertex.label.cex=.8, vertex.label.font=.8,layout=igraph::layout.kamada.kawai)
dev.off()
require(Rgraphviz)
require(topGO)
pdf("CNV_CC.tree.pdf")
plotGOgraph(egocc)
dev.off()
write.table(egocc,"CNV_CC.go.txt",quote=F,row.name=F,sep="\t")

egobp <- enrichGO(gene=transid$ENTREZID,OrgDb ="org.Hs.eg.db",ont="BP")
pdf("CNV_BP.dotplot.pdf",width=10,height=10)
dotplot(egobp, font.size=10,title="CNV gene BP",showCategory=15)
dev.off()
pdf("CNV_BP.map.pdf",width=10,height=10)
enrichMap(egobp, vertex.label.cex=.5, vertex.label.font=.5,layout=igraph::layout.kamada.kawai)
dev.off()
require(Rgraphviz)
require(topGO)
pdf("CNV_BP.tree.pdf")
plotGOgraph(egobp)
dev.off()
write.table(egobp,"CNV_BP.go.txt",quote=F,row.name=F,sep="\t")

egomf <- enrichGO(gene=transid$ENTREZID,OrgDb ="org.Hs.eg.db",ont="MF")
pdf("CNV_MF.dotplot.pdf",width=10,height=10)
dotplot(egomf, font.size=10,title="CNV gene MF",showCategory=15)
dev.off()
pdf("CNV_MF.map.pdf",width=10,height=10)
enrichMap(egomf, vertex.label.cex=.5, vertex.label.font=.5,layout=igraph::layout.kamada.kawai)
dev.off()
require(Rgraphviz)
require(topGO)
pdf("CNV_MF.tree.pdf")
plotGOgraph(egomf)
dev.off()
write.table(egomf,"CNV_MF.go.txt",quote=F,row.name=F,sep="\t")

ekk <- enrichKEGG(gene=transid$ENTREZID, keyType = "kegg",organism = "hsa", pvalueCutoff = 0.05, pAdjustMethod = "BH")
write.table(ekk,"CNV_kegg.txt",quote=F,row.name=F,sep="\t")
pdf("CNV_kegg.dotplot.pdf",width=10,height=10)
dotplot(ekk, font.size=10,title="CNV kegg",showCategory=15)
dev.off()


